#### Normalization Problem

In [3]:
import numpy as np

In [5]:
#Create a random 5x5 ndarray and store it in variable x
x = np.random.random((5,5))
#Normalize x using the given formula
z = ( x - np.mean(x) / np.std(x))
#Print the normalized x
print (z)

np.save('X_normalized', z)

[[-0.80494826 -1.52588937 -1.54831628 -1.08588226 -1.31526264]
 [-1.11557038 -1.56763342 -1.54511374 -1.51741371 -1.51029523]
 [-1.247719   -1.3555922  -1.50777903 -0.90871217 -0.95749692]
 [-1.21873121 -0.92029515 -0.95426164 -1.45903868 -0.82556337]
 [-1.0361297  -1.55226863 -1.32656974 -1.7165221  -0.98765352]]


#### Divisible by 3 Problem

In [9]:
import numpy as np

In [11]:
#Create a 10x10 ndarray with positive integers of 1-100
a = np.arange(1,101).reshape(10,10)
#Square the elements 
b = (np.array(a)**2)
#Store all the elements divisible by 3 in variable c
c = (b % 3 == 0)
#In variable d, return the elements that is divisible by 3 from variable b
d = b[c]

#Print a header for the squared elements
print("Squared elements")
#Print the squared values
print(b)
#Add space for aesthetic purposes
print()
#Print a header for the elements divisible by 3
print("Elements divisible by 3: ")
#Print the values divisible by 3
print(d)

#Save the result
np.save("div_by_3.npy", d)

Squared elements
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
